diff_drive_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 50.0
  pose_covariance_diagonal: [0.001, 0.001, 100.0, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 100.0, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 0.5
  wheel_separation: 0.34
  wheel_radius: 0.075
  enable_odom_tf: true

